apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}    # This becomes 'mysql' by default
  labels:
    app: {{ .Values.mysql.name }}   # Matches mysql pod label
spec:
  selector:
    app: {{ .Values.mysql.name }}   # Must match the label in mysql-deployment.yaml
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}          # Exposed service port (default: 3306)
      targetPort: {{ .Values.mysql.port }}    # Matches container port
