name: CI - Helm Chart Only

on:
  push:
    branches: [main]
    paths:
      - 'helm-chart/**'

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    outputs:
      image_tag: ${{ steps.set.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Set image tag from input
        id: set
        run: echo "image_tag=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT

  helm-deploy:
    needs: deploy
    uses: ./.github/workflows/deploy-app.yaml
    with:
      helm_release: loginapp
      image_tag: ${{ needs.deploy.outputs.image_tag }}
    secrets: inherit

  notify:
    needs: helm-deploy
    uses: ./.github/workflows/notify-discord.yaml
    with:
      status: ${{ needs.helm-deploy.result }}
      scope: Helm Chart Deploy
    secrets: inherit
