name: CI - Helm Chart Only

on:
  push:
    branches: [main]
    paths:
      - 'helm-chart/**'

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (Optional - leave empty to reuse last)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    outputs:
      image_tag: ${{ steps.set.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image-tag artifact
        if: ${{ !github.event.inputs.image_tag }}
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Set image tag
        id: set
        run: |
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            echo "image_tag=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=$(cat image-tag.txt)" >> $GITHUB_OUTPUT
          fi

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

  helm-deploy:
    needs: deploy
    uses: ./.github/workflows/deploy-app.yaml
    with:
      helm_release: loginapp
      image_tag: ${{ needs.deploy.outputs.image_tag }}
    secrets: inherit

  notify:
    needs: helm-deploy
    uses: ./.github/workflows/notify-discord.yaml
    with:
      status: ${{ needs.helm-deploy.result }}
      scope: Helm Chart Deploy
    secrets: inherit
