name: Reusable Helm Deploy

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      helm_release:
        required: true
        type: string

    secrets:
      SESSION_SECRET:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name cd-cluster

      - name: Lint Helm chart
        run: helm lint ./helm-chart

      - name: Render Helm template
        run: helm template ${{ inputs.helm_release }} ./helm-chart --set backend.image.tag=${{ inputs.image_tag }}

      - name: Deploy with Helm
        run: ./scripts/deploy.sh ${{ inputs.helm_release }} ${{ inputs.image_tag }}
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
