name: Notify Discord

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      scope:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      # You could optionally use `actions/checkout@v4.2.2` here if you need repo access
      - name: Send Discord Notification
        run: |
          STATUS_EMOJI="✅"
          if [[ "${{ inputs.status }}" == "failure" ]]; then
            STATUS_EMOJI="❌"
          fi

          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"$STATUS_EMOJI CI Job \`${{ inputs.scope }}\` ${STATUS_EMOJI} - Status: \`${{ inputs.status }}\` in \`${{ github.repository }}\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
